aixian/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),

    url(r'^app/', include('app.urls',namespace='app')),
]

app/urls.py
#name:urls
#author:Yangwenwu
#@Time:2018/7/24 19:46
from django.conf.urls import url, include
from django.contrib import admin

from app import views

urlpatterns = [
    url(r'^home/', views.home,name='home'),
    url(r'^market/', views.market,name='market'),
    url(r'^cart/', views.cart,name='cart'),
    url(r'^mine/', views.mine,name='main'),
]

app/models.py
from django.db import models

# Create your models here.
class Recommend(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)

    # 将父类定义为抽象类（不会创建表）
    class Meta:
        abstract = True

class Wheel(Recommend):
    class Meta:
        db_table = 'axf_wheel'


class Nav(Recommend):
    class Meta:
        db_table='axf_nav'

class Mustbuy(Recommend):
    class Meta:
        db_table = 'axf_mustbuy'

class Shop(Recommend):
    class Meta:
        db_table = 'axf_shop'

app/views.py
from django.shortcuts import render, redirect


# Create your views here.
from django.urls import reverse


def index(request):
    return redirect(reverse('app:home'))


def home(request):
    return render(request,'home.html')


def market(request):
    return render(request,'market.html')


def cart(request):
    return render(request,'cart.html')


def mine(request):
    return render(request,'mine.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>首页</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <style>

        #header{
            width: 100%;
            height: 60px;
            background-color:#f0e000;
            border-bottom: 1px solid lightgray;
            left: 0;
            top: 0;
        }
        #header ,.footer{
            position: fixed;
        }

        #header h3{
            text-align: center;
            line-height: 60px;
            font-size: .5rem;
            font-weight: normal;
        }
        .content{
            width: 100%;
            text-align: center;
            height: 1000px;
            background-color: #ffffff;
        }
        #footer{
            height: 60px;
            background-color: white;
            bottom: 0;
            left: 0;
            border-top: 1px solid #ccc;
        }
        #footer a{
            {#display: inline-block;#}
            {#width: 5rem;#}
            display: inline-block;
            width: 2.5rem;
            float: left;
            text-align: center;
            margin-top: .25rem;

        }
        #footer a:hover {
            -webkit-tap-highlight-color: transparent;
        }
        #footer img{
            width: 20px;


        }
        #footer a span, #footer a img {
            display: block;
            margin: 0 auto;
        }

        #footer  a span{
            font-size: .35rem;


        }
    </style>
    <script src="{% static 'js/jquery-3.1.1.js' %}"></script>
    <script type="text/javascript">
    
    $(function () {
        $screenWidth =$(window).innerWidth()
        $('html').css('font-size',$screenWidth/10)

    })
    
    
    </script>
</head>
<body>
<div class="header" id="header">
{% block header%}

    <h3>首页</h3>


{% endblock %}
</div>
<div class="content">
{% block content %}

    <div style="">首页内容</div>

{% endblock %}
</div>
{% block footer %}
<div class="footer" id="footer" >
    {% block homebtn %}
        <a href="{% url 'app:home' %}">
        <img src="{% static 'img/home.png' %}" alt="home">
        <span>首页</span>
    </a>
    {% endblock %}

    {% block  marketbtn%}
        <a href="{% url 'app:market' %}">
        <img src="{% static 'img/market.png' %}" alt="home">
        <span>闪购</span>
    </a>
    {% endblock %}

    {% block cartbtn%}
        <a href="{% url 'app:cart' %}">
        <img src="{% static 'img/cart.png' %}" alt="home">
        <span>购物车</span>
    </a>
    {% endblock %}

    {% block  minebtn%}
        <a href="{% url 'app:main' %}">
        <img src="{% static 'img/mine.png' %}" alt="home">
        <span>我的</span>
    </a>
    {% endblock %}




</div>
{% endblock %}
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block header %}

    <h3> 购物车</h3>


{% endblock %}
{% block content %}

    <div style="">我的购物车</div>

{% endblock %}
{% block cartbtn%}
        <a href="{% url 'app:cart' %}">
        <img src="{% static 'img/cart_selected.png' %}" alt="home">
        <span>购物车</span>
    </a>
    {% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block header %}

    <h3> 首页</h3>


{% endblock %}
{% block content %}

    <div style="">首页内容 </div>

{% endblock %}
{% block homebtn %}
        <a href="{% url 'app:home' %}">
        <img src="{% static 'img/home_selected.png' %}" alt="home">
        <span>首页</span>
    </a>
{% endblock %}

templates/market.html
{% extends 'base.html' %}
{% load static %}
{% block header %}

    <h3> 闪购</h3>


{% endblock %}
{% block content %}
    <div style="">wo de shangou </div>

{% endblock %}
{% block marketbtn %}
<a href="{% url 'app:market' %}">
    <img src="{% static 'img/market_selected.png' %}">
    <span>闪购7</span>
</a>
{% endblock %}

templates/mine.html
{% extends 'base.html' %}
{% load static %}
{% block header %}

    <h3> 我的</h3>


{% endblock %}
{% block content %}

    <div style="">wo de yemian </div>

{% endblock %}
{% block  minebtn%}
        <a href="{% url 'app:main' %}">
        <img src="{% static 'img/mine_selected.png' %}" alt="home">
        <span>我的</span>
    </a>
    {% endblock %}